#define MSJ_OPCION_AYUDA "Ingrese: .\\simpletron -h o .\\simpletron --help para mas informacion.\n"
#define MSJ_ST_ERROR_ARCHIVO_NO_ENCONTRADO "El archivo ingresado no se encuentra"
#define MSJ_ST_ERROR_PTR_NULO "Puntero nulo"
#define MSJ_ST_ERROR_MEMORIA "Ocurrio un error al pedir memoria"
/*validaciones*/
#define MSJ_ST_ERROR_MEMORIA_INGRESADA_INVALIDA "La memoria ingresada no es valida, la misma debe ser un entero positivo"
#define MSJ_ST_ERROR_FORMATO_ARCHIVO_INVALIDO "El formato de archivo de salida no es valido"
#define MSJ_ST_ERROR_STDIN_INVALIDO "stdin no valido"
#define MSJ_ST_ERROR_CANT_ARG "La cantidad de argumentos ingresados por la terminal no es valido."
/*carga.c*/
#define MSJ_ST_ERROR_CREAR_SIMPLETRON "Ocurrio un error al crear e inicializar el simpletron"
#define MSJ_ST_ERROR_LEER_PALABRA "Ocurrio un error al leer palabra del archivo"
#define MSJ_ST_ERROR_PALABRA_NO_VALIDA "La palabra ingresada no es valida"
/*ejecutar_codigo*/
#define MSJ_ST_HALT ""
#define MSJ_ST_ERROR_CAD_NO_ES_ENTERO ""
#define MSJ_ST_ERROR_PALABRA_FUERA_DE_RANGO ""
#define MSJ_ST_ERROR_SEGMENTATION_FAULT ""
#define MSJ_ST_ERROR_CAD_NO_LEIDA ""
#define MSJ_ST_ERROR_OPCODE_INVALIDO ""
#define MSJ_ST_ERROR_MAX_INSTR_SUPERADO ""
#define MSJ_ST_ERROR_MAX_INGRESOS_SUPERADO ""
#define MSJ_ST_ERROR_NODO_VACIO ""
#define MSJ_ST_ERROR_ESCRIBIR_BIN "Ocurrio un errror al esribir el archivo binario"
